name: compile

on:
  schedule:
    - cron:  '34 * * * *'
  push:
    branches: [ main, development ]
    paths:
      - 'src/**'
      - '.github/workflows/compile.yml'

  pull_request:
    branches: [ main, development ]
    paths:
      - 'src/**'
      - '.github/workflows/compile.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      with:
        path: 'main'

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Checkout bsb_lan
      uses: actions/checkout@v2
      with:
        repository: 'fredlcore/bsb_lan'
        path: 'bsb_lan'

    - name: Checkout bsbDef
      uses: actions/checkout@v2
      with:
        repository: 'fredlcore/bsbDef'
        path: 'bsbDef'

    - name: build
      working-directory: main/
      run: ./compile.sh 

    - name: copy
      run: mv -f main/all.json bsbDef/index.json 

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Autogenerated
        file_pattern: '*.json'
        repository: bsbDef
